# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/lua_loader/ui/MainWindow.ui'
#
# Created: Thu Feb 19 22:18:12 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1080, 720)
        self.main_widget = QtGui.QWidget(MainWindow)
        self.main_widget.setObjectName(_fromUtf8("main_widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.main_widget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.file_tree_view = QtGui.QVBoxLayout()
        self.file_tree_view.setSpacing(0)
        self.file_tree_view.setObjectName(_fromUtf8("file_tree_view"))
        self.horizontalLayout_2.addLayout(self.file_tree_view)
        self.tab_view = QtGui.QTabWidget(self.main_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_view.sizePolicy().hasHeightForWidth())
        self.tab_view.setSizePolicy(sizePolicy)
        self.tab_view.setObjectName(_fromUtf8("tab_view"))
        self.horizontalLayout_2.addWidget(self.tab_view)
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_file = QtGui.QMenu(self.menubar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_settings = QtGui.QMenu(self.menubar)
        self.menu_settings.setObjectName(_fromUtf8("menu_settings"))
        self.menu_help = QtGui.QMenu(self.menubar)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        self.menu_view = QtGui.QMenu(self.menubar)
        self.menu_view.setObjectName(_fromUtf8("menu_view"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menu_file_quit = QtGui.QAction(MainWindow)
        self.menu_file_quit.setObjectName(_fromUtf8("menu_file_quit"))
        self.menu_preferences = QtGui.QAction(MainWindow)
        self.menu_preferences.setObjectName(_fromUtf8("menu_preferences"))
        self.action_Log = QtGui.QAction(MainWindow)
        self.action_Log.setObjectName(_fromUtf8("action_Log"))
        self.menu_about = QtGui.QAction(MainWindow)
        self.menu_about.setObjectName(_fromUtf8("menu_about"))
        self.menu_view_files = QtGui.QAction(MainWindow)
        self.menu_view_files.setCheckable(True)
        self.menu_view_files.setChecked(False)
        self.menu_view_files.setEnabled(False)
        self.menu_view_files.setObjectName(_fromUtf8("menu_view_files"))
        self.menu_view_actions = QtGui.QAction(MainWindow)
        self.menu_view_actions.setCheckable(True)
        self.menu_view_actions.setChecked(True)
        self.menu_view_actions.setObjectName(_fromUtf8("menu_view_actions"))
        self.action_GPIO = QtGui.QAction(MainWindow)
        self.action_GPIO.setCheckable(True)
        self.action_GPIO.setChecked(True)
        self.action_GPIO.setObjectName(_fromUtf8("action_GPIO"))
        self.action_Wireless = QtGui.QAction(MainWindow)
        self.action_Wireless.setCheckable(True)
        self.action_Wireless.setChecked(True)
        self.action_Wireless.setObjectName(_fromUtf8("action_Wireless"))
        self.menu_view_log = QtGui.QAction(MainWindow)
        self.menu_view_log.setObjectName(_fromUtf8("menu_view_log"))
        self.menu_file_new = QtGui.QAction(MainWindow)
        self.menu_file_new.setObjectName(_fromUtf8("menu_file_new"))
        self.menu_file_open = QtGui.QAction(MainWindow)
        self.menu_file_open.setObjectName(_fromUtf8("menu_file_open"))
        self.menu_file_save = QtGui.QAction(MainWindow)
        self.menu_file_save.setObjectName(_fromUtf8("menu_file_save"))
        self.menu_file_save_as = QtGui.QAction(MainWindow)
        self.menu_file_save_as.setObjectName(_fromUtf8("menu_file_save_as"))
        self.menu_file_close = QtGui.QAction(MainWindow)
        self.menu_file_close.setObjectName(_fromUtf8("menu_file_close"))
        self.action_Cut = QtGui.QAction(MainWindow)
        self.action_Cut.setObjectName(_fromUtf8("action_Cut"))
        self.action_Copy = QtGui.QAction(MainWindow)
        self.action_Copy.setObjectName(_fromUtf8("action_Copy"))
        self.action_Paste = QtGui.QAction(MainWindow)
        self.action_Paste.setObjectName(_fromUtf8("action_Paste"))
        self.action_Delete = QtGui.QAction(MainWindow)
        self.action_Delete.setObjectName(_fromUtf8("action_Delete"))
        self.actionSelect_All = QtGui.QAction(MainWindow)
        self.actionSelect_All.setObjectName(_fromUtf8("actionSelect_All"))
        self.menu_file.addAction(self.menu_file_new)
        self.menu_file.addAction(self.menu_file_open)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.menu_file_save)
        self.menu_file.addAction(self.menu_file_save_as)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.menu_file_close)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.menu_file_quit)
        self.menu_settings.addAction(self.menu_preferences)
        self.menu_help.addAction(self.menu_about)
        self.menu_view.addAction(self.menu_view_actions)
        self.menu_view.addAction(self.menu_view_files)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.menu_view_log)
        self.menu_Edit.addAction(self.action_Cut)
        self.menu_Edit.addAction(self.action_Copy)
        self.menu_Edit.addAction(self.action_Paste)
        self.menu_Edit.addAction(self.action_Delete)
        self.menu_Edit.addAction(self.actionSelect_All)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_settings.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_view.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ESP8266 LuaLoader", None))
        self.menu_file.setTitle(_translate("MainWindow", "&File", None))
        self.menu_settings.setTitle(_translate("MainWindow", "&Settings", None))
        self.menu_help.setTitle(_translate("MainWindow", "&Help", None))
        self.menu_view.setTitle(_translate("MainWindow", "&View", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menu_file_quit.setText(_translate("MainWindow", "&Quit", None))
        self.menu_file_quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.menu_preferences.setText(_translate("MainWindow", "&Preferences", None))
        self.action_Log.setText(_translate("MainWindow", "&Log", None))
        self.menu_about.setText(_translate("MainWindow", "&About", None))
        self.menu_view_files.setText(_translate("MainWindow", "&Files", None))
        self.menu_view_actions.setText(_translate("MainWindow", "&Actions", None))
        self.action_GPIO.setText(_translate("MainWindow", "&GPIO", None))
        self.action_Wireless.setText(_translate("MainWindow", "&Wireless", None))
        self.menu_view_log.setText(_translate("MainWindow", "&Log", None))
        self.menu_file_new.setText(_translate("MainWindow", "&New...", None))
        self.menu_file_open.setText(_translate("MainWindow", "&Open...", None))
        self.menu_file_save.setText(_translate("MainWindow", "&Save", None))
        self.menu_file_save_as.setText(_translate("MainWindow", "Save &As...", None))
        self.menu_file_close.setText(_translate("MainWindow", "&Close", None))
        self.action_Cut.setText(_translate("MainWindow", "Cu&t", None))
        self.action_Cut.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.action_Copy.setText(_translate("MainWindow", "&Copy", None))
        self.action_Copy.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.action_Paste.setText(_translate("MainWindow", "&Paste", None))
        self.action_Paste.setShortcut(_translate("MainWindow", "Ctrl+V", None))
        self.action_Delete.setText(_translate("MainWindow", "&Delete", None))
        self.actionSelect_All.setText(_translate("MainWindow", "Select &All", None))
        self.actionSelect_All.setShortcut(_translate("MainWindow", "Ctrl+A", None))

